version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'p:teal'
template = '{{ .Path }} '

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:pink'
background = 'transparent'
template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} *{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_status = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:peach{{end}}",
]
background = 'transparent'
template = '❯'

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'p:yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'

[blocks.segments.properties]
threshold = 5000

[transient_prompt]
foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:peach{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'p:peach'
background = 'transparent'
template = '❯❯ '

[palette]
blue = '#89B4FA'
peach = '#FAB387'
red = '#F38BA8'
green = '#A6E3A1'
teal = '#94E2D5'
yellow = '#F9E2AF'
lavender = '#B4BEFE'
pink = '#F5C2E7'
