#!/usr/bin/env sh

# global settings
yabai -m config                                 \
      layout bsp                                \
      window_placement second_child             \
      top_padding 8                             \
      bottom_padding 8                          \
      left_padding 8                            \
      right_padding 8                           \
      window_gap 8                             \
      mouse_follows_focus off                   \
      mouse_modifier alt 		        \
      mouse_action1 move                        \
      mouse_action2 resize                      \
      mouse_drop_action swap

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off


echo "yabai configuration loaded.."
