#!/usr/bin/env sh

# global settings
yabai -m config \
	layout bsp \
	window_placement second_child \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 8 \
	mouse_follows_focus off \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# Signal to unzoom a window when focus is switched to another window
yabai -m signal --add event=window_focused action="\
    zoom_window=\$(yabai -m query --windows --window recent | jq -r '.[\"has-fullscreen-zoom\"]'); \
    if [ \$zoom_window = true ]; then \
        yabai -m window recent --toggle zoom-fullscreen; \
    fi"

# make JetBrains products popup windows float
apps='^IntelliJ IDEA$'
yabai -m rule --add app="JetBrains Toolbox" manage=off
yabai -m rule --add app="${apps}" manage=off
yabai -m rule --add app="${apps}" title="( – )" manage=on

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

borders active_color=0xffe1e3e4 style=round width=5.0 &

echo "yabai configuration loaded.."
